import Footer from "./components/Footer";
import Header from "./components/Header";
import "./styles/index.scss";
import { roboto } from "./ui/fonts";

export const metadata = {
  title: "Filmoteka",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="wrapper">
          <h1 className="visually-hidden">Filmoteka</h1>
          <Header />
          <main>
             {children} 
          </main>
        
          <Footer />
        </div>
      </body>
    </html>
  );
}
