import Provider from "./provider";

import "./styles/index.scss";
import { roboto } from "./ui/fonts";

export const metadata = {
  title: "Filmoteka",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
